#!/usr/bin/env node
// QIS-Skills publisher.
//
// Reads the PRIVATE master catalog (studio/catalog.json, git-ignored) and writes only
// what is public into the static site:
//   - generated regions in qis-skills/index.html   (<!-- qis:begin NAME --> … <!-- qis:end NAME -->)
//   - one page per public skill                     (qis-skills/<id>/index.html)
//   - live counts on any page                       (<span data-qis="live-count">…</span>)
//   - sitemap.xml
// Hidden skills never leave your machine; coming-soon skills publish as a teaser only.
//
// Usage:
//   node tools/publish-skills.mjs                 publish as of today
//   node tools/publish-skills.mjs --dry-run       show what would be public, write nothing
//   node tools/publish-skills.mjs --date 2026-11-01 --dry-run   preview a future release date
//   QIS_CATALOG=/path/to/catalog.json node tools/publish-skills.mjs

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const DEFAULT_CATALOG = process.env.QIS_CATALOG || path.join(ROOT, 'studio', 'catalog.json');
const SITE = 'https://aniteshshaw.github.io';
const GENERATED_MARK = '<!-- generated by tools/publish-skills.mjs — edit studio/catalog.json, not this file -->';
const EMAIL = 'emailanitesh@gmail.com';

export const STATUSES = ['live', 'preview', 'coming-soon', 'hidden'];
const CATEGORY = { core: 'Core pipeline', specialist: 'Specialist', utility: 'Utility' };

// ---------------------------------------------------------------- helpers
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
// Local calendar date (not UTC), so a release dated today goes live today in your time zone.
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`; };
const fmtDate = (iso) => new Date(iso + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' });

function wrap(text, max) {
  const words = String(text).split(/\s+/);
  const lines = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > max && line) { lines.push(line); line = w; }
    else line = (line + ' ' + w).trim();
  }
  if (line) lines.push(line);
  return lines;
}
// wrap() capped at n lines, with an ellipsis when text was cut.
const clip = (text, max, n) => {
  const lines = wrap(text, max);
  if (lines.length <= n) return lines;
  const out = lines.slice(0, n);
  out[n - 1] = out[n - 1].replace(/[,.;:]?$/, '…');
  return out;
};

// ---------------------------------------------------------------- icons (24px line icons, original)
export const ICONS = {
  clipboard: '<rect x="5.5" y="4" width="13" height="17" rx="2"/><path d="M9 4h6v3H9z"/><path d="m9 13.5 2 2 4-4.5"/>',
  pen: '<path d="M4 20h4L19 9l-4-4L4 16z"/><path d="m13 7 4 4"/>',
  browser: '<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18"/><path d="m9.5 12.5-2 2 2 2M14.5 12.5l2 2-2 2"/>',
  gate: '<path d="M12 3 5 6v6c0 4.5 3 7.5 7 9 4-1.5 7-4.5 7-9V6z"/><path d="m9 12 2 2 4-4"/>',
  link: '<path d="M10 14a4 4 0 0 0 5.7 0l3-3a4 4 0 0 0-5.7-5.7l-1 1"/><path d="M14 10a4 4 0 0 0-5.7 0l-3 3a4 4 0 0 0 5.7 5.7l1-1"/>',
  bug: '<rect x="8" y="7" width="8" height="12" rx="4"/><path d="M12 11v8M4.5 10H8M16 10h3.5M4.5 15.5H8M16 15.5h3.5M9.5 7.5 7.5 4.5M14.5 7.5l2-3"/>',
  a11y: '<circle cx="12" cy="4.5" r="1.8"/><path d="M5 8.5c4 1 10 1 14 0M12 9.5v5M12 14.5 9 21M12 14.5 15 21"/>',
  plug: '<path d="M9 3v5M15 3v5M6 8h12v3a6 6 0 0 1-12 0zM12 17v4"/>',
  refresh: '<path d="M20 8A8 8 0 0 0 6 5.5L4 7.5"/><path d="M4 3.5v4h4"/><path d="M4 16a8 8 0 0 0 14 2.5l2-2"/><path d="M20 20.5v-4h-4"/>',
  chart: '<path d="M4 20V4M4 20h16"/><path d="m7.5 15 3.5-4 3 3 5-6"/>',
  pulse: '<path d="M3 12h4l2-6 4 12 2-6h6"/>',
  search: '<circle cx="11" cy="11" r="6"/><path d="m20 20-4.5-4.5"/>',
  scale: '<path d="M12 4v16M7.5 20h9M5 8h14"/><path d="m5 8-2.5 5.5h5zM19 8l-2.5 5.5h5z"/>',
  phone: '<rect x="7" y="2.5" width="10" height="19" rx="2.5"/><path d="M11 18h2"/>',
  android: '<rect x="5" y="9.5" width="14" height="10" rx="2.5"/><path d="M8 9.5a4 4 0 0 1 8 0M7.5 5l1.8 2.4M16.5 5l-1.8 2.4"/><path d="M9.5 14h.01M14.5 14h.01"/>',
  target: '<circle cx="12" cy="12" r="8.5"/><circle cx="12" cy="12" r="4.5"/><path d="M12 12h.01"/>',
  diagram: '<rect x="3" y="3" width="7" height="5" rx="1"/><rect x="14" y="16" width="7" height="5" rx="1"/><rect x="14" y="3" width="7" height="5" rx="1"/><path d="M10 5.5h4M17.5 8v8"/>',
  palette: '<path d="M12 3a9 9 0 1 0 0 18c1.5 0 2-1 2-2s-1-1.5-1-2.5 1-1.5 2-1.5h2a4 4 0 0 0 4-4c0-4.5-4-8-9-8z"/><path d="M7.5 11h.01M10 7h.01M15 7.5h.01"/>',
  shield: '<path d="M12 3 5 6v6c0 4.5 3 7.5 7 9 4-1.5 7-4.5 7-9V6z"/>',
  chat: '<path d="M4 5h16v11H9l-5 4z"/>',
  check: '<path d="m5 12.5 4.5 4.5L19 7.5"/>',
  arrow: '<path d="M5 12h14M13 6l6 6-6 6"/>',
  lock: '<rect x="5" y="11" width="14" height="10" rx="2"/><path d="M8 11V8a4 4 0 0 1 8 0v3"/>',
  spark: '<path d="M12 3v4M12 17v4M3 12h4M17 12h4M6 6l2.5 2.5M15.5 15.5 18 18M18 6l-2.5 2.5M8.5 15.5 6 18"/>'
};
export const icon = (key, cls = 'ico') =>
  `<svg class="${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[key] || ICONS.spark}</svg>`;

// ---------------------------------------------------------------- catalog + resolution
export function loadCatalog(file = DEFAULT_CATALOG) {
  if (!fs.existsSync(file)) {
    throw new Error(`Private catalog not found at ${file}\nRestore it from your backup, or set QIS_CATALOG=/path/to/catalog.json`);
  }
  const catalog = JSON.parse(fs.readFileSync(file, 'utf8'));
  validate(catalog);
  return catalog;
}

export function validate(catalog) {
  const errors = [];
  const ids = new Set();
  for (const s of catalog.skills || []) {
    if (!/^[a-z0-9-]+$/.test(s.id || '')) errors.push(`invalid id "${s.id}"`);
    if (ids.has(s.id)) errors.push(`duplicate id "${s.id}"`);
    ids.add(s.id);
    if (!STATUSES.includes(s.status)) errors.push(`${s.id}: status must be one of ${STATUSES.join(', ')}`);
    if (!CATEGORY[s.category]) errors.push(`${s.id}: category must be core, specialist, or utility`);
    if (s.publishAfter && !/^\d{4}-\d{2}-\d{2}$/.test(s.publishAfter)) errors.push(`${s.id}: publishAfter must be YYYY-MM-DD`);
    if (!Array.isArray(s.flow) || s.flow.length < 3 || s.flow.length > 6) errors.push(`${s.id}: flow needs 3–6 steps`);
  }
  if (errors.length) throw new Error('Catalog is invalid:\n  - ' + errors.join('\n  - '));
}

// The status a skill has on a given date: a scheduled date promotes it to live.
export function resolveStatus(skill, date = today()) {
  if (skill.publishAfter && skill.publishAfter <= date && skill.status !== 'live') return 'live';
  return skill.status;
}

export function plan(catalog, date = today()) {
  const skills = catalog.skills.slice().sort((a, b) => a.order - b.order)
    .map((s) => ({ ...s, resolved: resolveStatus(s, date) }));
  return {
    date,
    product: catalog.product,
    public: skills.filter((s) => s.resolved === 'live' || s.resolved === 'preview'),
    teaser: skills.filter((s) => s.resolved === 'coming-soon'),
    hidden: skills.filter((s) => s.resolved === 'hidden'),
    scheduled: skills.filter((s) => s.publishAfter && s.publishAfter > date)
  };
}

// ---------------------------------------------------------------- blueprint diagrams
// A "blueprint" is a hand-sketched flow: terminal → steps → terminal, with an animated
// packet travelling the line, each stage lighting up as it arrives, and one handwritten note.
let bpSeq = 0;
function blueprint({ nodes, startLabel, endLabel, note, sheet, linkPrefix = '' }) {
  const id = 'bp' + (++bpSeq);
  return blueprintH({ id, nodes, startLabel, endLabel, note, sheet, linkPrefix }) +
         blueprintV({ id: id + 'v', nodes, startLabel, endLabel, note, linkPrefix });
}


function svgDefs(id) {
  return `<defs>
    <pattern id="${id}-grid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0v24" fill="none" class="bp-grid"/></pattern>
    <filter id="${id}-ink" x="-5%" y="-5%" width="110%" height="110%"><feTurbulence type="fractalNoise" baseFrequency="0.03" numOctaves="2" seed="7"/><feDisplacementMap in="SourceGraphic" scale="1.6"/></filter>
    <marker id="${id}-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M1 1l8 4-8 4" fill="none" class="bp-arrowhead"/></marker>
  </defs>`;
}

function blueprintH({ id, nodes, startLabel, endLabel, note, sheet, linkPrefix }) {
  const W = 1100, H = sheet ? 330 : 300;
  const tx0 = 40, tx1 = W - 40, cy = 172;
  const n = nodes.length;
  const bw = n >= 6 ? 128 : 150, bh = 118;
  const x0 = 104, x1 = W - 104;
  const step = n > 1 ? (x1 - x0 - bw) / (n - 1) : 0;
  const boxes = nodes.map((nd, i) => ({ ...nd, x: x0 + i * step, cx: x0 + i * step + bw / 2 }));
  const linePath = `M${tx0} ${cy} H${tx1}`;
  let s = `<svg class="bp bp--h" data-axis="x" data-from="${tx0}" data-to="${tx1}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="${id}-t" xmlns="http://www.w3.org/2000/svg">
  <title id="${id}-t">${esc(nodes.map((nd, i) => `${i + 1}. ${nd.title}`).join(', '))}</title>${svgDefs(id)}
  <rect width="${W}" height="${H}" fill="url(#${id}-grid)"/>
  <g filter="url(#${id}-ink)">
    <path d="${linePath}" class="bp-line"/>
    <path d="${linePath}" class="bp-flow"/>
    <circle cx="${tx0}" cy="${cy}" r="20" class="bp-term"/>
    <circle cx="${tx1}" cy="${cy}" r="20" class="bp-term bp-term--end"/>
  </g>
  <g transform="translate(${tx0 - 9} ${cy - 9}) scale(.75)" class="bp-ico">${ICONS.chat}</g>
  <g transform="translate(${tx1 - 9} ${cy - 9}) scale(.75)" class="bp-ico bp-ico--end">${ICONS.check}</g>
  <text x="${tx0}" y="${cy + 44}" class="bp-term-label" text-anchor="middle">${esc(startLabel)}</text>
  <text x="${tx1}" y="${cy + 44}" class="bp-term-label" text-anchor="middle">${esc(endLabel)}</text>
  <circle r="7" cx="${tx0}" cy="${cy}" class="bp-packet"/>`;
  boxes.forEach((b, i) => {
    const title = clip(b.title, n >= 6 ? 14 : 16, 2);
    const sub = b.sub ? clip(b.sub, n >= 6 ? 15 : 18, 2) : [];
    const by = cy - bh / 2;
    const inner = `
    <g class="bp-node" data-a="${b.x}" data-b="${b.x + bw}">
      <rect x="${b.x}" y="${by}" width="${bw}" height="${bh}" rx="10" class="bp-box" filter="url(#${id}-ink)"/>
      <text x="${b.x + 14}" y="${by + 22}" class="bp-num">${String(i + 1).padStart(2, '0')}</text>
      ${b.icon ? `<g transform="translate(${b.x + bw - 32} ${by + 9}) scale(.8)" class="bp-ico">${ICONS[b.icon] || ''}</g>` : ''}
      ${title.map((t, k) => `<text x="${b.x + 14}" y="${by + 46 + k * 19}" class="bp-title">${esc(t)}</text>`).join('')}
      ${sub.map((t, k) => `<text x="${b.x + 14}" y="${by + 46 + title.length * 19 + 4 + k * 15}" class="bp-sub">${esc(t)}</text>`).join('')}
    </g>`;
    s += b.href ? `<a href="${linkPrefix}${b.href}" class="bp-link" aria-label="${esc(b.title)} — open skill">${inner}</a>` : inner;
    if (b.artifact) {
      s += `<text x="${b.cx}" y="${by + bh + 30}" class="bp-artifact" text-anchor="middle">→ ${esc(b.artifact)}</text>`;
    }
  });
  if (note && boxes[note.step - 1]) {
    const b = boxes[note.step - 1];
    const textX = Math.min(Math.max(b.cx + 10, 150), W - 170);
    const anchor = textX > W - 260 ? 'end' : 'start';
    const tX = anchor === 'end' ? Math.min(b.cx + 120, W - 24) : textX;
    s += `<text x="${tX}" y="58" class="bp-note" text-anchor="${anchor}">${esc(note.text)}</text>
    <path d="M${anchor === 'end' ? tX - 60 : tX + 14} 68 C ${b.cx + 26} 80, ${b.cx + 4} 88, ${b.cx} ${cy - bh / 2 - 8}" class="bp-note-arrow" marker-end="url(#${id}-arr)"/>`;
  }
  if (sheet) {
    s += `<g class="bp-sheet"><rect x="${W - 330}" y="${H - 34}" width="310" height="24" rx="3"/><text x="${W - 320}" y="${H - 17}">${esc(sheet)}</text></g>`;
  }
  return s + '</svg>';
}

function blueprintV({ id, nodes, startLabel, endLabel, note, linkPrefix }) {
  const W = 360, bw = 268, bh = 78, gap = 34, top = 74;
  const cx = 168, x = cx - bw / 2;
  const H = top + nodes.length * (bh + gap) + 52;
  const ty0 = 30, ty1 = H - 30;
  const linePath = `M${cx} ${ty0} V${ty1}`;
  let s = `<svg class="bp bp--v" data-axis="y" data-from="${ty0}" data-to="${ty1}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="${id}-t" xmlns="http://www.w3.org/2000/svg">
  <title id="${id}-t">${esc(nodes.map((nd, i) => `${i + 1}. ${nd.title}`).join(', '))}</title>${svgDefs(id)}
  <rect width="${W}" height="${H}" fill="url(#${id}-grid)"/>
  <g filter="url(#${id}-ink)">
    <path d="${linePath}" class="bp-line"/><path d="${linePath}" class="bp-flow"/>
    <circle cx="${cx}" cy="${ty0}" r="18" class="bp-term"/><circle cx="${cx}" cy="${ty1}" r="18" class="bp-term bp-term--end"/>
  </g>
  <g transform="translate(${cx - 8} ${ty0 - 8}) scale(.68)" class="bp-ico">${ICONS.chat}</g>
  <g transform="translate(${cx - 8} ${ty1 - 8}) scale(.68)" class="bp-ico bp-ico--end">${ICONS.check}</g>
  <text x="${cx + 28}" y="${ty0 + 5}" class="bp-term-label">${esc(startLabel)}</text>
  <text x="${cx + 28}" y="${ty1 + 5}" class="bp-term-label">${esc(endLabel)}</text>
  <circle r="6" cx="${cx}" cy="${ty0}" class="bp-packet"/>`;
  nodes.forEach((nd, i) => {
    const y = top + i * (bh + gap);
    const title = clip(nd.title, 26, 1);
    const sub = clip(nd.sub || (nd.artifact ? '→ ' + nd.artifact : ''), 30, 2);
    const inner = `<g class="bp-node" data-a="${y}" data-b="${y + bh}">
      <rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="10" class="bp-box" filter="url(#${id}-ink)"/>
      <text x="${x + 14}" y="${y + 24}" class="bp-num">${String(i + 1).padStart(2, '0')}</text>
      <text x="${x + 46}" y="${y + 25}" class="bp-title">${esc(title[0])}</text>
      ${sub.map((t, k) => `<text x="${x + 46}" y="${y + 46 + k * 15}" class="bp-sub">${esc(t)}</text>`).join('')}
    </g>`;
    s += nd.href ? `<a href="${linkPrefix}${nd.href}" class="bp-link" aria-label="${esc(nd.title)} — open skill">${inner}</a>` : inner;
    if (note && note.step === i + 1) {
      s += `<text x="${W - 8}" y="${y - 9}" class="bp-note bp-note--sm" text-anchor="end">${esc(note.text)}</text>`;
    }
  });
  return s + '</svg>';
}

// ---------------------------------------------------------------- shared page chrome
function head({ title, description, canonical, depth }) {
  const up = '../'.repeat(depth);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}" />
<meta name="author" content="Anitesh Kumar Shaw" />
<link rel="canonical" href="${canonical}" />
<meta property="og:type" content="website" />
<meta property="og:url" content="${canonical}" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="${esc(description)}" />
<meta property="og:image" content="${SITE}/assets/og-image.png" />
<meta name="twitter:card" content="summary_large_image" />
<link rel="icon" href="${up}assets/favicon.svg" type="image/svg+xml" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Outfit:wght@500;600;700&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500;700&family=Caveat:wght@500;700&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="${up}css/style.css?v=20261001d" />
<script>document.documentElement.classList.add('js');</script>
</head>`;
}

function header(depth) {
  const up = '../'.repeat(depth);
  return `<a class="skip-link" href="#main">Skip to main content</a>
<header class="site-header">
  <nav class="nav" aria-label="Primary">
    <a class="nav__logo" href="${up}"><span class="nav__logo-mark">AS</span><span class="nav__logo-sub">QIS-Skills</span></a>
    <button class="nav__toggle" id="navToggle" aria-expanded="false" aria-controls="navMenu" aria-label="Open navigation menu">
      <span class="nav__bar" aria-hidden="true"></span><span class="nav__bar" aria-hidden="true"></span><span class="nav__bar" aria-hidden="true"></span>
    </button>
    <ul class="nav__menu" id="navMenu">
      <li><a href="${up}qis-skills/#pipeline">Pipeline</a></li>
      <li><a href="${up}qis-skills/#anatomy">How it's built</a></li>
      <li><a href="${up}qis-skills/#catalog">All skills</a></li>
      <li><a href="${up}qis-skills/#access">Demo &amp; access</a></li>
      <li><a href="${up}" class="nav__cta">Anitesh Shaw →</a></li>
    </ul>
  </nav>
</header>`;
}

function footer(depth) {
  const up = '../'.repeat(depth);
  return `<footer class="footer">
  <div class="container footer__inner">
    <nav class="footer__nav" aria-label="Footer">
      <a href="${up}">Portfolio</a>
      <a href="${up}qis-skills/">QIS-Skills</a>
      <a href="${up}#book">The Book</a>
      <a href="${up}resume/">Resume</a>
    </nav>
    <p class="footer__note"><span id="footerYear"></span> Anitesh Kumar Shaw · Tampa, FL</p>
  </div>
</footer>
<script src="${up}js/main.js?v=20261001d"></script>`;
}

const statusBadge = (s) => {
  const map = { live: ['Live', 'status--live'], preview: ['Preview', 'status--preview'], 'coming-soon': ['Coming soon', 'status--soon'] };
  const [label, cls] = map[s.resolved] || map.live;
  return `<span class="status ${cls}">${label}</span>` + (s.featured ? '<span class="status status--flag">Flagship</span>' : '');
};

// ---------------------------------------------------------------- skill page
function skillPage(skill, ctx) {
  const { publicSkills, core } = ctx;
  const idx = publicSkills.findIndex((s) => s.id === skill.id);
  const prev = publicSkills[idx - 1];
  const next = publicSkills[idx + 1];
  const coreIdx = core.findIndex((s) => s.id === skill.id);
  const canonical = `${SITE}/qis-skills/${skill.id}/`;
  const demoHref = `mailto:${EMAIL}?subject=${encodeURIComponent('QIS-Skills demo — ' + skill.name)}`;
  const flowNodes = skill.flow.map((f) => ({ title: f.title, sub: f.sub }));
  const diagram = blueprint({
    nodes: flowNodes, startLabel: 'you ask', endLabel: 'you decide', note: skill.note,
    sheet: `QIS-SKILLS · ${skill.id} · REV ${ctx.version}`
  });
  const whereItSits = coreIdx >= 0 ? `
  <section class="section section--tight" aria-labelledby="sits-title">
    <div class="container">
      <span class="section__label">Where it sits</span>
      <h2 class="section__title" id="sits-title">Stage ${coreIdx + 1} of ${core.length} in the core pipeline</h2>
      <ol class="mini-pipe">
        ${core.map((c, i) => `<li class="mini-pipe__item${c.id === skill.id ? ' is-current' : ''}"><a href="../${c.id}/"${c.id === skill.id ? ' aria-current="page"' : ''}><span class="mini-pipe__ico">${icon(c.icon)}</span><span class="mini-pipe__name">${esc(c.name)}</span><span class="mini-pipe__art">${esc(c.artifact || '')}</span></a></li>`).join('')}
      </ol>
    </div>
  </section>` : '';
  const figure = skill.image ? `
      <figure class="one-pager">
        <img src="../../${esc(skill.image)}" alt="One-page visual summary of the ${esc(skill.name)} skill" loading="lazy" width="1254" height="1254" />
        <figcaption>One-page summary · ${esc(skill.name)}</figcaption>
      </figure>` : '';

  return `${head({ title: `${skill.name} — QIS-Skills | Anitesh Shaw`, description: `${skill.tagline}. ${skill.description}`.slice(0, 300), canonical, depth: 2 })}
<body class="page-skill">
${GENERATED_MARK}
${header(2)}
<main id="main">
  <section class="skill-hero" aria-labelledby="skill-title">
    <div class="skill-hero__glow" aria-hidden="true"></div>
    <div class="container skill-hero__grid">
      <div class="skill-hero__copy">
        <nav class="crumbs" aria-label="Breadcrumb"><a href="../">QIS-Skills</a><span aria-hidden="true">/</span><a href="../#catalog">${CATEGORY[skill.category]}</a></nav>
        <div class="skill-hero__id">
          <span class="icon-tile icon-tile--lg">${icon(skill.icon)}</span>
          <div class="skill-hero__meta">${statusBadge(skill)}<code class="slug">${esc(skill.id)}</code></div>
        </div>
        <h1 id="skill-title">${esc(skill.name)}</h1>
        <p class="skill-hero__tagline">${esc(skill.tagline)}</p>
        <p class="skill-hero__desc">${esc(skill.description)}</p>
        <p class="metric-chip">${icon('spark')}${esc(skill.highlight)}</p>
        <div class="hero__ctas">
          <a class="btn btn--primary" href="${demoHref}">See it run live</a>
          <a class="btn btn--secondary" href="../#catalog">All skills</a>
        </div>
      </div>
      <aside class="prompt-card" aria-label="Example requests that trigger this skill">
        <div class="prompt-card__bar"><span></span><span></span><span></span><em>Copilot Chat · Agent mode</em></div>
        <div class="prompt-card__body">
          <span class="prompt-card__label">Just ask —</span>
          ${skill.prompts.map((p) => `<p class="prompt-card__prompt"><span aria-hidden="true">›</span> ${esc(p)}</p>`).join('\n          ')}
          <p class="prompt-card__route">${icon('arrow')} routes to <code>${esc(skill.id)}</code></p>
        </div>
        <ul class="chip-row" aria-label="Works with">${skill.stack.map((t) => `<li>${esc(t)}</li>`).join('')}</ul>
      </aside>
    </div>
  </section>

  <section class="section" aria-labelledby="how-title">
    <div class="container">
      <span class="section__label">How it works</span>
      <h2 class="section__title" id="how-title">The playbook, sketched</h2>
      <p class="section__lead">${esc(skill.howItWorks)}</p>
      <figure class="blueprint reveal">
        ${diagram}
        <figcaption>Each stage lights up as the request moves through it. The handwritten note marks the step that makes this skill trustworthy.</figcaption>
      </figure>
    </div>
  </section>

  <section class="section section--alt" aria-labelledby="why-title">
    <div class="container split">
      <div class="reveal">
        <span class="section__label">Why it exists</span>
        <h2 class="section__title" id="why-title">The problem it solves</h2>
        <p class="prose">${esc(skill.whyItMatters)}</p>
      </div>
      <div class="guard-card reveal">
        <span class="section__label">Guardrails</span>
        <h3>Built-in discipline</h3>
        <p class="prose prose--sm">${esc(skill.keyDiscipline)}</p>
        <ul class="guard-list">
          ${skill.guardrails.map((g) => `<li>${icon('shield')}<span>${esc(g)}</span></li>`).join('\n          ')}
        </ul>
      </div>
    </div>
  </section>

  <section class="section" aria-labelledby="io-title">
    <div class="container">
      <span class="section__label">Contract</span>
      <h2 class="section__title" id="io-title">What goes in, what comes out</h2>
      <div class="io-flow reveal">
        <div class="io-flow__col">
          <h3>Inputs</h3>
          <ul>${skill.inputs.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>
        </div>
        <div class="io-flow__core" aria-hidden="true">
          <span class="io-flow__ring"></span>
          <span class="icon-tile icon-tile--lg">${icon(skill.icon)}</span>
          <span class="io-flow__name">${esc(skill.name)}</span>
        </div>
        <div class="io-flow__col io-flow__col--out">
          <h3>Outputs</h3>
          <ul>${skill.outputs.map((x) => `<li>${esc(x)}</li>`).join('')}</ul>
        </div>
      </div>${figure}
    </div>
  </section>
${whereItSits}
  <section class="section section--tight">
    <div class="container">
      <nav class="pager" aria-label="More skills">
        ${prev ? `<a class="pager__link" href="../${prev.id}/"><span>← Previous</span><strong>${esc(prev.name)}</strong></a>` : '<span></span>'}
        ${next ? `<a class="pager__link pager__link--next" href="../${next.id}/"><span>Next →</span><strong>${esc(next.name)}</strong></a>` : '<span></span>'}
      </nav>
      <div class="cta-band reveal">
        <div>
          <h2>Want to watch ${esc(skill.name)} work on a real story?</h2>
          <p>The source is private. I run live demos inside VS Code and can grant temporary repo access to interview panels.</p>
        </div>
        <a class="btn btn--primary" href="${demoHref}">Request a demo</a>
      </div>
    </div>
  </section>
</main>
${footer(2)}
</body>
</html>
`;
}

// ---------------------------------------------------------------- product-page regions
// When no skill is public the product page still has to read well, so these regions
// fall back to generic, name-free content: no skill ids, names, or links leave the machine.
const GENERIC_STAGES = [
  { title: 'Story review', artifact: 'Readiness notes', icon: 'clipboard' },
  { title: 'Test design', artifact: 'Test cases', icon: 'pen' },
  { title: 'Automation', artifact: 'Playwright specs', icon: 'browser' },
  { title: 'PR review', artifact: 'Review verdict', icon: 'gate' },
  { title: 'Evidence', artifact: 'Linked results', icon: 'link' },
  { title: 'Triage', artifact: 'Filed defects', icon: 'bug' }
];
const GENERIC_DEMOS = [
  { name: 'Story review', label: 'story readiness', prompt: 'Is story #4821 ready for sprint?',
    steps: ['Read the story and its parent epic', 'Checked 6 sibling stories', 'Scanned validation rules in the code', 'Looked up existing test cases'],
    title: 'Not ready yet', lines: [{ kind: 'warn', text: '3 acceptance criteria are vague' }, { kind: 'info', text: '2 questions only the PO can answer' }, { kind: 'ok', text: 'Suggested estimate: 5 points, medium confidence' }] },
  { name: 'PR review', label: 'PR review gate', prompt: 'Can I merge PR 912?',
    steps: ['Confirmed it is a test-automation PR', 'Checked what each assertion proves', 'Looked for fixed sleeps and flaky waits', 'Matched tests to acceptance criteria'],
    title: 'Needs work · 72 / 100', lines: [{ kind: 'block', text: 'A 3-second sleep will flake in CI' }, { kind: 'warn', text: 'One acceptance criterion has no assertion' }, { kind: 'info', text: 'Comments drafted. Post them?' }] },
  { name: 'Accessibility', label: 'accessibility audit', prompt: 'Check checkout against WCAG 2.1 AA',
    steps: ['Parsed 6 components', 'Ran the Trusted Tester checks', 'Checked contrast, focus order, labels', 'Mapped findings to WCAG and Section 508'],
    title: '7 findings · 2 critical', lines: [{ kind: 'block', text: 'Two inputs have no programmatic label' }, { kind: 'warn', text: 'Focus ring is invisible on 3 buttons' }, { kind: 'ok', text: 'Conformance report drafted' }] }
];

function regionStats(p, core) {
  if (!p.public.length) {
    return `<ul class="kpis" aria-label="QIS-Skills at a glance">
        <li class="kpi"><span class="kpi__value kpi__value--word">Private</span><span class="kpi__label">beta, shown live on request</span></li>
        <li class="kpi"><span class="kpi__value">6</span><span class="kpi__label">stages from story to release</span></li>
        <li class="kpi"><span class="kpi__value">60–70%</span><span class="kpi__label">less QA analysis &amp; design effort*</span></li>
        <li class="kpi"><span class="kpi__value">${icon('spark')}</span><span class="kpi__label">Technology Innovation Award</span></li>
      </ul>`;
  }
  return `<ul class="kpis" aria-label="QIS-Skills at a glance">
        <li class="kpi"><span class="kpi__value" data-count="${p.public.length}">${p.public.length}</span><span class="kpi__label">skills live</span></li>
        <li class="kpi"><span class="kpi__value" data-count="${core.length}">${core.length}</span><span class="kpi__label">stage core pipeline</span></li>
        <li class="kpi"><span class="kpi__value">60–70%</span><span class="kpi__label">less QA analysis &amp; design effort*</span></li>
        <li class="kpi"><span class="kpi__value">${icon('spark')}</span><span class="kpi__label">Technology Innovation Award</span></li>
      </ul>`;
}

function regionPipeline(core) {
  if (!core.length) {
    return `<figure class="blueprint blueprint--pipeline reveal">
        ${blueprint({
          nodes: GENERIC_STAGES.map((g) => ({ title: g.title, icon: g.icon, artifact: g.artifact })),
          startLabel: 'new story', endLabel: 'release-ready',
          note: { step: 4, text: 'agents prepare · humans approve' },
          sheet: 'QIS · STORY → RELEASE'
        })}
        <figcaption>One skill per stage. Each one hands its output to the next.</figcaption>
      </figure>`;
  }
  return `<figure class="blueprint blueprint--pipeline reveal">
        ${blueprint({
          nodes: core.map((s) => ({ title: s.name, href: `${s.id}/`, icon: s.icon, artifact: s.artifact })),
          startLabel: 'new story', endLabel: 'release-ready',
          note: { step: Math.min(4, core.length), text: 'agents prepare · humans approve' },
          sheet: 'QIS-SKILLS · CORE PIPELINE · STORY → RELEASE'
        })}
        <figcaption>Click any stage to open its skill. Each output feeds the next stage.</figcaption>
      </figure>`;
}

function regionCatalog(p) {
  if (!p.public.length) {
    return `<div class="private-panel reveal">
          <span class="icon-tile icon-tile--lg">${icon('lock')}</span>
          <div>
            <h3>The catalog is private for now</h3>
            <p>I'm keeping the individual skills out of public view while QIS-Skills is in private beta. If you want to see them, I'm happy to walk you through the whole library live and show a few running on a sample project.</p>
            <a class="btn btn--primary" href="mailto:${EMAIL}?subject=${encodeURIComponent('QIS-Skills walkthrough')}">Ask for a walkthrough</a>
          </div>
        </div>`;
  }
  return `<div class="catalog-toolbar" role="group" aria-label="Filter skills">
        <button class="catalog-filter is-active" type="button" data-filter="all" aria-pressed="true">All</button>
        <button class="catalog-filter" type="button" data-filter="featured" aria-pressed="false">Flagship</button>
        <button class="catalog-filter" type="button" data-filter="core" aria-pressed="false">Core pipeline</button>
        <button class="catalog-filter" type="button" data-filter="specialist" aria-pressed="false">Specialists</button>
        <button class="catalog-filter" type="button" data-filter="utility" aria-pressed="false">Utilities</button>
      </div>
      <p class="visually-hidden" aria-live="polite" id="catalogStatus"></p>
      <div class="skill-catalog">
        ` + p.public.map((s, i) => `<article class="skill-card reveal" data-category="${s.category}" data-featured="${s.featured ? 'true' : 'false'}" style="--i:${i}">
          <div class="skill-card__top">
            <span class="icon-tile">${icon(s.icon)}</span>
            <div class="skill-card__badges">${statusBadge(s)}</div>
          </div>
          <h3 class="skill-card__name"><a href="${s.id}/">${esc(s.name)}</a></h3>
          <p class="skill-card__tagline">${esc(s.tagline)}</p>
          <ol class="skill-card__flow" aria-label="Workflow">${s.flow.map((f) => `<li>${esc(f.title)}</li>`).join('')}</ol>
          <p class="skill-card__highlight">${esc(s.highlight)}</p>
          <span class="skill-card__cat">${CATEGORY[s.category]}</span>
        </article>`).join('\n        ') + `
      </div>`;
}

function regionHomePipeline(core) {
  if (!core.length) {
    return `<ol class="band-pipe" aria-label="Where the skills work, story to release">
          ${GENERIC_STAGES.map((g, i) => `<li style="--i:${i}"><span class="band-pipe__row"><span class="band-pipe__ico">${icon(g.icon)}</span><span class="band-pipe__name">${esc(g.title)}</span><span class="band-pipe__art">${esc(g.artifact)}</span></span></li>`).join('\n          ')}
        </ol>`;
  }
  return `<ol class="band-pipe" aria-label="QIS-Skills core pipeline">
          ${core.map((s, i) => `<li style="--i:${i}"><a href="qis-skills/${s.id}/"><span class="band-pipe__ico">${icon(s.icon)}</span><span class="band-pipe__name">${esc(s.name)}</span><span class="band-pipe__art">${esc(s.artifact || '')}</span></a></li>`).join('\n          ')}
        </ol>`;
}

function regionRoadmap(p) {
  const upcoming = p.teaser.slice().sort((a, b) => (a.publishAfter || '9999').localeCompare(b.publishAfter || '9999'));
  if (!upcoming.length) return '';
  return `<section id="roadmap" class="section section--alt" aria-labelledby="roadmap-title">
    <div class="container">
      <span class="section__label">Release train</span>
      <h2 class="section__title" id="roadmap-title">Coming next</h2>
      <p class="section__lead">Skills in final hardening. Each ships when it clears the same guardrail review as the rest of the catalog.</p>
      <ol class="roadmap">
        ${upcoming.map((s) => `<li class="roadmap__item reveal">
          <span class="roadmap__date">${s.publishAfter ? fmtDate(s.publishAfter) : 'Soon'}</span>
          <span class="icon-tile">${icon(s.icon)}</span>
          <div><h3>${esc(s.name)}</h3><p>${esc(s.tagline)}</p></div>
        </li>`).join('\n        ')}
      </ol>
    </div>
  </section>`;
}

function regionDemo(p) {
  let demos = p.public.filter((s) => s.demo).map((s) => ({ id: s.id, label: s.id, name: s.name, icon: s.icon, ...s.demo }));
  if (!demos.length) demos = GENERIC_DEMOS;
  return `<script type="application/json" id="qis-demos">${JSON.stringify(demos).replace(/</g, '\\u003c')}</script>`;
}

function replaceRegion(html, name, content, file) {
  const re = new RegExp(`(<!-- qis:begin ${name} -->)[\\s\\S]*?(<!-- qis:end ${name} -->)`);
  if (!re.test(html)) throw new Error(`${file}: missing region markers for "${name}"`);
  return html.replace(re, `$1\n${content}\n$2`);
}

function replaceCounts(html, counts) {
  return html.replace(/(<span data-qis="([a-z-]+)">)[^<]*(<\/span>)/g, (m, open, key, close) =>
    counts[key] !== undefined ? open + counts[key] + close : m);
}

function sitemap(publicSkills, date) {
  const urls = ['/', '/qis-skills/', '/personal/', '/resume/', ...publicSkills.map((s) => `/qis-skills/${s.id}/`)];
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${SITE}${u}</loc><lastmod>${date}</lastmod></url>`).join('\n')}
</urlset>
`;
}

// ---------------------------------------------------------------- publish
export function publish({ catalogPath = DEFAULT_CATALOG, date = today(), dryRun = false } = {}) {
  bpSeq = 0;
  const catalog = loadCatalog(catalogPath);
  const p = plan(catalog, date);
  const core = p.public.filter((s) => s.category === 'core');
  const ctx = { publicSkills: p.public, core, version: catalog.product?.version || '1.0' };
  const written = [];
  const removed = [];

  if (!dryRun) {
    // 1. Product page regions
    const productFile = path.join(ROOT, 'qis-skills', 'index.html');
    let html = fs.readFileSync(productFile, 'utf8');
    html = replaceRegion(html, 'stats', regionStats(p, core), productFile);
    html = replaceRegion(html, 'pipeline', regionPipeline(core), productFile);
    html = replaceRegion(html, 'catalog', regionCatalog(p), productFile);
    html = replaceRegion(html, 'roadmap', regionRoadmap(p), productFile);
    html = replaceRegion(html, 'demos', regionDemo(p), productFile);
    fs.writeFileSync(productFile, html);
    written.push('qis-skills/index.html');

    const homeFile = path.join(ROOT, 'index.html');
    fs.writeFileSync(homeFile, replaceRegion(fs.readFileSync(homeFile, 'utf8'), 'home-pipeline', regionHomePipeline(core), homeFile));
    written.push('index.html');

    // 2. One page per public skill
    for (const s of p.public) {
      const dir = path.join(ROOT, 'qis-skills', s.id);
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(path.join(dir, 'index.html'), skillPage(s, ctx));
      written.push(`qis-skills/${s.id}/index.html`);
    }

    // 3. Remove pages for skills that are no longer public (only ones this script generated)
    const keep = new Set(p.public.map((s) => s.id));
    for (const entry of fs.readdirSync(path.join(ROOT, 'qis-skills'), { withFileTypes: true })) {
      if (!entry.isDirectory() || keep.has(entry.name)) continue;
      const f = path.join(ROOT, 'qis-skills', entry.name, 'index.html');
      if (fs.existsSync(f) && fs.readFileSync(f, 'utf8').includes(GENERATED_MARK)) {
        fs.rmSync(path.join(ROOT, 'qis-skills', entry.name), { recursive: true });
        removed.push(`qis-skills/${entry.name}/`);
      }
    }

    // 4. Live counts on every page that shows them
    const counts = { 'live-count': p.public.length, 'core-count': core.length };
    for (const rel of ['index.html', 'personal/index.html', 'qis-skills/index.html', 'resume/index.html']) {
      const f = path.join(ROOT, rel);
      const before = fs.readFileSync(f, 'utf8');
      const after = replaceCounts(before, counts);
      if (after !== before) { fs.writeFileSync(f, after); if (!written.includes(rel)) written.push(rel); }
    }

    // 5. Sitemap
    fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), sitemap(p.public, date));
    written.push('sitemap.xml');
  }

  return {
    date,
    public: p.public.map((s) => ({ id: s.id, name: s.name, status: s.resolved, featured: !!s.featured })),
    teaser: p.teaser.map((s) => ({ id: s.id, name: s.name, publishAfter: s.publishAfter })),
    hidden: p.hidden.map((s) => ({ id: s.id, name: s.name, publishAfter: s.publishAfter })),
    scheduled: p.scheduled.map((s) => ({ id: s.id, name: s.name, publishAfter: s.publishAfter, status: s.status })),
    written, removed
  };
}

export function formatSummary(r, dryRun) {
  const lines = [];
  lines.push(`QIS-Skills ${dryRun ? 'preview' : 'publish'} as of ${r.date}`);
  lines.push(`  Public  (${r.public.length}): ${r.public.map((s) => s.name + (s.featured ? ' ★' : '') + (s.status === 'preview' ? ' [preview]' : '')).join(', ') || '—'}`);
  lines.push(`  Teased  (${r.teaser.length}): ${r.teaser.map((s) => `${s.name}${s.publishAfter ? ' → ' + s.publishAfter : ''}`).join(', ') || '—'}`);
  lines.push(`  Private (${r.hidden.length}): ${r.hidden.map((s) => `${s.name}${s.publishAfter ? ' → ' + s.publishAfter : ''}`).join(', ') || '—'}  (never written to the site)`);
  if (r.scheduled.length) lines.push(`  Scheduled: ${r.scheduled.map((s) => `${s.name} goes live ${s.publishAfter}`).join('; ')}`);
  if (!dryRun) {
    lines.push(`  Wrote ${r.written.length} files${r.removed.length ? `, removed ${r.removed.join(', ')}` : ''}.`);
    lines.push('  Next: review locally, then commit and push.');
  }
  return lines.join('\n');
}

// ---------------------------------------------------------------- CLI
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const di = args.indexOf('--date');
  const date = di >= 0 ? args[di + 1] : today();
  try {
    const r = publish({ date, dryRun });
    console.log(formatSummary(r, dryRun));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
